name: dart_hue
description: An SDK designed for the Dart language that enables developers to
  easily integrate Philips Hue smart devices into their applications.
version: 2.0.0
repository: https://github.com/babincc/dart_hue
issue_tracker: https://github.com/babincc/dart_hue/issues

topics:
  - philips-hue
  - smart-lights

funding:
  - https://www.buymeacoffee.com/babincc
  - https://paypal.me/cssbabin
  - https://venmo.com/u/babincc

environment:
  sdk: ^3.3.3

dependencies:
  collection: ^1.17.0
  color: ^3.0.0
  crypto: ^3.0.6
  dtls2: ^0.18.1
  http: ^1.0.0
  multicast_dns: ^0.3.2+7

dev_dependencies:
  test: ^1.25.15
  lints: ^5.0.0
